### ISSUE TITLE
catkin_make installでインストールされないファイルがあります

### ISSUE THREAD

**Issue by ShotaAk** [rt-net/sciurus17_ros#110]
# 不具合の概要

`catkin_make install`コマンドを実行してもインストールされないファイルがあります。

`sciurus17_gazebo`のlaunchファイルと、`sciurus17_examples`のいくつかのスクリプトがインストールされません。

# 実行環境

- OS: ubuntu18.04
- ソフトのバージョン: 2020/12/22 master最新

# 再現方法

1. 'catkin_make install' を実行する
2. installディレクトリが生成される
3. installディレクトリ内にsciurus17_rosの生成物が格納されるが、`sciurus17_gazebo`や`sciurus17_examples`の生成物に不備があります

# 期待する動作

`sciurus17_gazebo`のlaunchファイルが`install/share/*`ディレクトリに、
`sciurus17_examples`のスクリプトファイルが`install/lib/*`ディレクトリに格納される。

# その他

不具合の原因はCMakeLists.txtの不備です。
install()コマンドを実行が抜けています。

※下記はsciurus17_descriptionのCMakeLists.txt
https://github.com/rt-net/sciurus17_ros/blob/79c1ed6f5f3bd1775312860ae803bae14e1591e4/sciurus17_description/CMakeLists.txt#L26-L33

sciurus17_examplesに関しては、スクリプトファイルが増減しても影響しないように書き直しが必要です。
https://github.com/rt-net/sciurus17_ros/blob/79c1ed6f5f3bd1775312860ae803bae14e1591e4/sciurus17_examples/CMakeLists.txt#L45-L56

**Comment by Tiryoh** [comment]
sciurus17_descriptionの`CMakeLists.txt`では`foreach(dir config launch meshes urdf) `を使っていましたが、以下のようにまとめて`DIRECTORY`を列挙するのでも問題ないようです。

```cmake
install(DIRECTORY launch models worlds maps rviz
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
```
https://github.com/Tiryoh/aws-robomaker-small-warehouse-world/blob/master/CMakeLists.txt
