### ISSUE TITLE
`ros2 launch sciurus17_examples example.launch.py -s`で候補に出てこないサンプルがある

### ISSUE THREAD

**Issue by chama1176** [rt-net/sciurus17_ros#165]
# 不具合の概要

`ros2 launch sciurus17_examples example.launch.py -s`で候補に出てこないサンプルがあります
サンプル追加時に更新が漏れていそうです

# 実行環境

- OS: 
- ソフトのバージョン: 

# 再現方法

1. '...' を実行する
2. '...' を実行する
3. '...' を実行する
4. 不具合が発生する

# 期待する動作

# ログ・画像

```sh
# コマンド実行ログがあればここに貼り付けてください
```

# その他

**Comment by Kuwamai** [comment]
@chama1176 
確認したところ問題なさそうです。example.launch.pyで実行可能なサンプルはこれで全てで、他のサンプルは別のlaunchファイルで実行するようになっているかと思います。
https://github.com/rt-net/sciurus17_ros/blob/19765410448c85b91cd70a1d570aead0539e423f/sciurus17_examples/launch/example.launch.py#L61-L63

**Comment by chama1176** [comment]
@Kuwamai 
カメラサンプルはlaunchも別だったんですね、勘違いしていました
