### ISSUE TITLE
rgbd_launchが無いとエラーが出る

### ISSUE THREAD

**Issue by nomumuRT** [rt-net/sciurus17_ros#44]
```
roslaunch sciurus17_bringup sciurus17_bringup.launch
```
を実行すると表題のエラーが発生する。
realsense wrapper側で実行時dependが足りて無さそうに見える。

**Comment by nomumuRT** [comment]
Sciurus17側でdependに追加するのは戸惑われるので対応方法で悩み中。
このエラーが出た場合、次のようにインストールを行う事で解決することは確認済
```
apt-get install ros-kinetic-rgbd-launch
```

**Comment by shotahirama** [comment]
https://github.com/intel-ros/realsense/issues/678
上記で言及されている`rs_camera.launch`を使えば、エラーが発生しないことを確認しました。

**Comment by nomumuRT** [comment]
確認ありがとうございます！
呼び出し方を変えることによって減るトピックも確認しておいて下さい。機能が大きく損なわれることがないか気になります。サンプルコードで使用しているトピックはそのまま維持したいので、トピック名の違いはrenameなど活用してみて下さい。
問題解決できればPRもよろしくお願いします!
