### ISSUE TITLE
Gazeboのグリッパ制御方法の変更

### ISSUE THREAD

**Issue by nomumuRT** [rt-net/sciurus17_ros#50]
現在、グリッパの制御をmimic_control.pyで実現しているが、この実装はGazeboが推奨する方法ではないので変更した方が良い。
mimic_joint_pluginとSDFのgearboxどちらも検討したが、それぞれ課題があったので再調査が必要である。どちらでも動くようになるならサンプルとして価値が高い方を選択したい。

**Comment by ShotaAk** [comment]
mimic_joint_pluginで動作することを確認しました。
mimic_joint_pluginは、aptに対応していないので、別途git cloneしなければなりません。

https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins

**Comment by nomumuRT** [comment]
なるほど。インストール手順に考慮が必要なのはちょっと面倒ですね。
SDFのgearboxも調査よろしくお願いします。

**Comment by ShotaAk** [comment]
#61 でmimic_joint_pluginを取り入れてます。
gearboxは使用しません。
