### ISSUE TITLE
MoveIt!のBenchmark対応を検討する

### ISSUE THREAD

**Issue by nomumu** [rt-net/sciurus17_ros#51]
現状のsciurus17_rosパッケージはMoveIt!のBenchmarkへの対応が未実施である。
http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/benchmarking/benchmarking_tutorial.html
対応するメリットとコストについて調査し、実装要否を検討したい。

**Comment by ShotaAk** [comment]
benchmark対応の要望が出るまで一旦クローズします。
