### ISSUE TITLE
melodic対応

### ISSUE THREAD

**Issue by nomumu** [rt-net/sciurus17_ros#54]
Sciurus17のROSパッケージはどうやらmelodicでも動くようだが、アールティでエビデンスが取れてない。
正式にサポートを表明したいので、動作検証してkineticと異なる箇所があればbranchを分けて対応コードを公開したいと考えています。

**Comment by ShotaAk** [comment]
基本はCRANE-X7_ROS と同じ症状がでる。
https://github.com/rt-net/crane_x7_ros/issues/84

**Comment by ShotaAk** [comment]
melodic環境で実機を用いたサンプルがすべて実行できることを確認しました。

**Comment by ShotaAk** [comment]
#73 で対応済み。
