### ISSUE TITLE
プリセットゲインサンプルの参照トピック修正

### ISSUE THREAD

**Issue by nomumu** [rt-net/sciurus17_ros#63]
preset_pid_gain_example.pyが`preset_gain_no`トピックへPublishしているが、名前空間が変更になっており動作していないように見えます。
```
    if __name__ == '__main__':
        # PIDゲインプリセット用のPublisher
        pub_preset = rospy.Publisher("preset_gain_no", UInt8, queue_size=1)
```
sciurus17_bringupで起動した場合、`/sciurus17/preset_gain_no`が正しいように見えるので修正を検討したいです。

**Comment by ShotaAk** [comment]
コードは問題ありませんでした。

READMEを読むと、他のサンプルと同様に`rosrun`を実行してしまうかもしれません。
READMEを修正します。
https://github.com/rt-net/sciurus17_ros/tree/master/sciurus17_examples

**Comment by nomumu** [comment]
おっと勘違いでしたか。
README修正よろしくお願いします。
