### ISSUE TITLE
トルク制御モード公開方法の検討

### ISSUE THREAD

**Issue by nomumu** [rt-net/sciurus17_ros#80]
現状のSciurus17でもトルク制御モードに切り替え可能だが、複数の懸念により正式リリースできていない。
切り替え手段、ROSサンプル、ドキュメンテーションについて公開の方法を検討する。

**Comment by nomumu** [comment]
リリースを検討中の重力補償＋トルク制御を組み込んだSciurus17について、ROSCon2019 MACAUで展示し反応を見てみることにしました。これはPosition制御の目標値に対してやわらかく動くタイプのソフトウェアになります。認識できていない人や周辺環境にぶつかっても力をいなす動きをするため教材としての安全性が増します。
Effortを直接指定できる版は教材として危険度がむしろ上がるため、まだ安全なリリース方法を探っている状況です。

**Comment by nomumu** [comment]
ROSCon2019 MACAUからバージョンアップしたサンプルをSI2019にて展示する予定となった。   
リリース内容はイメージできてきたので、SI2019での反響も加味してリリース時期を決めようかと考え中です。

**Comment by ShotaAk** [comment]
#108、#109 にて電流制御のサンプルを追加したため、本Issueをクローズします。
