### ISSUE TITLE
頭部Realsenseカメラの2Dピクセルから世界座標系の3D座標に変換し方

### ISSUE THREAD

**Issue by tuantd** [rt-net/sciurus17_ros#93]
頭部カメラのカラー画像と深層画像を用いて、どうすればカラー画像の一つのピクセルから世界座標系の3D座標に変換出来ますか？
宜しくお願い申し上げます。

**Comment by ShotaAk** [comment]
頭部カメラにはIntealのRealSenseを使用しています。

座標変換（点群データの生成）はRealSense側で実行されているので、そちらを参照してください。

RealSense SDK:
https://github.com/IntelRealSense/librealsense

realsense_ros:
https://github.com/IntelRealSense/realsense-ros
